from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


def generate_pdf(
    report_text: str,
    output_path: str = "report.pdf",
) -> str:
    """
    PDF REPORT RENDERER
    ===================

    Purpose
    -------
    Converts the structured report text (generated by the LLM)
    into a professionally formatted academic-style PDF document.

    IMPORTANT:
    This function does NOT generate content.
    It ONLY handles visual layout and formatting.

    The report text must already contain structural markers:

        @@TITLE@@
        <actual title>
        @@TITLE@@

        @@Section Heading@@

    These markers are inserted earlier by the report writer.
    This module simply interprets them and applies styles.

    Inputs
    ------
    report_text : str
        Fully generated report containing title markers and
        section heading markers.

    output_path : str
        Path where the final PDF will be saved.

    Output
    ------
    str
        Path to the generated PDF file.
    """

    # --------------------------------------------------
    # Base stylesheet
    # --------------------------------------------------
    # Start with ReportLab’s default styles, then add custom ones.
    styles = getSampleStyleSheet()

    # --------------------------------------------------
    # Title Style (centered, larger font)
    # --------------------------------------------------
    styles.add(
        ParagraphStyle(
            name="TitleStyle",
            fontSize=18,
            leading=22,
            spaceBefore=24,
            spaceAfter=24,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        )
    )

    # --------------------------------------------------
    # Section Header Style
    # --------------------------------------------------
    styles.add(
        ParagraphStyle(
            name="SectionHeader",
            fontSize=13,
            leading=16,
            spaceBefore=18,
            spaceAfter=12,
            fontName="Helvetica-Bold",
        )
    )

    # --------------------------------------------------
    # Body Paragraph Style
    # --------------------------------------------------
    styles.add(
        ParagraphStyle(
            name="ReportBody",
            fontSize=11,
            leading=15,
            spaceBefore=6,
            spaceAfter=6,
        )
    )

    # --------------------------------------------------
    # Create document template
    # --------------------------------------------------
    # LETTER size with academic margins
    doc = SimpleDocTemplate(
        output_path,
        pagesize=LETTER,
        rightMargin=1 * inch,
        leftMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=1 * inch,
    )

    story = []  # Holds all visual elements in order

    # Split report into lines for marker-based parsing
    lines = report_text.splitlines()
    i = 0

    # --------------------------------------------------
    # Parse report text line by line
    # --------------------------------------------------
    while i < len(lines):
        line = lines[i].strip()

        # Blank line → vertical spacing
        if not line:
            story.append(Spacer(1, 12))
            i += 1
            continue

        # ---------- TITLE BLOCK ----------
        # Pattern:
        # @@TITLE@@
        # Actual title
        # @@TITLE@@
        if line == "@@TITLE@@":
            title_text = lines[i + 1].strip()
            story.append(Paragraph(title_text, styles["TitleStyle"]))
            story.append(Spacer(1, 24))
            i += 3  # skip marker, title, closing marker
            continue

        # ---------- SECTION HEADER ----------
        # Pattern: @@Heading Name@@
        if line.startswith("@@") and line.endswith("@@"):
            heading = line.strip("@")
            story.append(Paragraph(heading, styles["SectionHeader"]))
            story.append(Spacer(1, 12))
            i += 1
            continue

        # ---------- BODY PARAGRAPH ----------
        # Regular narrative text
        story.append(Paragraph(line, styles["ReportBody"]))
        i += 1

    # --------------------------------------------------
    # Build and save PDF
    # --------------------------------------------------
    doc.build(story)
    return output_path
